name: Bug Report
description: Please do not use bug reports for support issues or feature requests.
labels: ['status:not-yet-viewed', 'bug']
assignees: 'meisnate12'

body:
  - type: markdown
    attributes:
      value: >
        **THIS IS NOT THE PLACE TO ASK FOR SUPPORT OR FEATURE REQUESTS!**
        Please use [Plex Meta Manager Discord](https://discord.gg/NfH6mGFuAB) and post your question under the `pmm-help` channel for support issues.
        Please use [Plex Meta Manager Features](https://features.metamanager.wiki/) to request and upvote features.
  - type: input
    id: version
    attributes:
      label: Version Number
      description: Can be found at the beginning of your log file
      placeholder: eg. 1.16.0
    validations:
      required: true
  - type: dropdown
    id: branch
    attributes:
      label: What branch are you on?
      options:
        - master
        - develop
        - nightly
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Relevant Collection/Overlay/Playlist Definition
      description: >
        If you issue is happening with a specific collection/overlay/playlist please paste your definition here
        This will be automatically formatted into code, so no need for backticks.
      render: yml
  - type: input
    id: logs
    attributes:
      label: Logs
      description: >
        Please share the relevant log file with the error on [Gist](https://gist.github.com).
      placeholder: "https://gist.github.com"